// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://hhhzugqimtypijkdxxsm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhoaHp1Z3FpbXR5cGlqa2R4eHNtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjgxMDMzNDcsImV4cCI6MjA4MzY3OTM0N30.n9-aAw15Obt5hRc2fOcXbz9M39P9e2cpb3stIxct7nc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);